management:
  endpoints:
    web:
      basePath: /actuator
      exposure:
        include: "*" #"gateway,routes,health,info"
spring:
  cloud:
    gateway:
      actuator:
        verbose:
          enabled: false # 上面的 gateway才会生效
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:9876/ # 数组
        apiPath: instances