spring:
  cloud:
    gateway:
      defaultFilters:
        - name: Hystrix
          args:
            name: defaultFallback
            fallbackUri: forward:/gateway-hystrix/fallback
      routes:
        - id: sc-user-provider-id
          uri: http://localhost:8081/
          order: 0
          predicates:
            - Path=/api-user/** # 构造方法方式
            - Weight=userGroup,5
          filters:
            - StripPrefix=1
        - id: sc-user-provider-id2
          uri: http://localhost:8787/
          order: 0
          predicates:
            - Path=/api-user/** # 构造方法方式
            - Weight=userGroup,5
          filters:
            - StripPrefix=1
        - id: sc-consumer-id
          uri: http://localhost:8079/
          order: 0
          predicates:
            - name: Path
              args:
                patterns: /api-consumer/**
          filters:
            - StripPrefix=1
        - id: sc-order-provider-id
          uri: http://localhost:8083/
          order: 0
          predicates:
            - name: Path
              args:
                patterns: /api-order/**
          filters:
            - StripPrefix=1