spring:
  resources:
    staticLocations:
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/
  profiles:
    include: gateway,tomcat,zipkin,sba,eureka,ribbon
    active: local