spring:
  zipkin:
    baseUrl: "http://localhost:9411"
  sleuth:
    sampler:
      probability: 1
    messaging:
      kafka:
        enabled: false
  profiles:
    include: zipkin-kafka

---
spring:
  profiles: zipkin-kafka
  zipkin:
    sender:
      type: kafka
    kafka:
      topic: game_sc-demo_zipkin
  kafka:
    #    bootstrapServers: 10.20.8.92:9092,10.20.2.4:9092,10.20.11.104:9092
    #    bootstrap-servers: dev.game.game.sg2.kafka:9092
    bootstrapServers: dev.zipkin.sc-demo.game.sg2.mq:9092
    topic: game_sc-demo_zipkin
    producer:
      #      bootstrap-servers: 10.20.8.92:9092,10.20.2.4:9092,10.20.11.104:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 1
    consumer:
      group-id: game
      auto-commit-interval: 1000ms
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 1