spring:
  zipkin:
    baseUrl: sc-zipkin-server # 该项sender http方式上报才有意义
    sender:
      type: kafka
    kafka:
      topic: game_zipkin_collector # zipkin使用的kafka跟业务kafka共享bootstrapServers，但是zipkin有自己的topic、自己的生产者！！ ZipkinKafkaSenderConfiguration.ZipkinKafkaSenderBeanConfiguration
  sleuth:
    sampler:
      probability: 1
    messaging:
      kafka:
        enabled: false
  profiles:
    include: zipkin-kafka