spring:
  profiles:
    active: local
    include: tomcat,feign,hystrix,ribbon
  mvc:
    servlet:
      loadOnStartup: 1
management:
  endpoints:
    web:
      basePath: /actuator
      exposure:
        include: "*"
---
spring:
  profiles: local

---
spring:
  profiles: dev

---
spring:
  profiles: prod