spring:
  zipkin:
    baseUrl: "http://localhost:9411"
  sleuth:
    sampler:
      probability: 1
  profiles:
    active: zipkin-kafka

---
spring:
  profiles: zipkin-kafka
  zipkin:
    sender:
      type: kafka
    kafka:
      topic: game_sc-demo_zipkin
  kafka:
    bootstrapServers: dev.zipkin.sc-demo.game.sg2.mq:9092
    topic: game_sc-demo_zipkin
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 1
    consumer:
      group-id: myz-game
      auto-commit-interval: 1000ms
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 1