spring:
  profiles:
    active: local
    include: tomcat,feign,sentinel,hystrix,ribbon,zipkin,eureka,sba
  mvc:
    servlet:
      loadOnStartup: 1
management:
  endpoints:
    web:
      basePath: /actuator
      exposure:
        include: "*"
my:
  data: myz
---
spring:
  profiles: local
  kafka:
    bootstrapServers: dev.zipkin.sc-demo.game.sg2.mq:9092
#    topic: 自己的业务topic（跟zipkin的topic不一样）
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      retries: 1
    consumer:
      group-id: game
      auto-commit-interval: 1000ms
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 1
---
spring:
  profiles: dev
  kafka:
    bootstrapServers: dev.zipkin.sc-demo.game.sg2.mq:9092
#    topic: 自己的业务topic（跟zipkin的topic不一样）
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      retries: 1
    consumer:
      group-id: game
      auto-commit-interval: 1000ms
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 1
---
spring:
  profiles: prod
  kafka:
    bootstrapServers: dev.zipkin.sc-demo.game.sg2.mq:9092
#    topic: 自己的业务topic（跟zipkin的topic不一样）
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      retries: 1
    consumer:
      group-id: game
      auto-commit-interval: 1000ms
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 1