spring:
  profiles:
    active: local
    include: tomcat,feign,hystrix,ribbon
  mvc:
    servlet:
      loadOnStartup: 1

---
spring:
  profiles: local

---
spring:
  profiles: dev

---
spring:
  profiles: prod