spring:
  profiles:
    active: local
    include: tomcat,feign,sentinel,hystrix,ribbon,zipkin,sba
  mvc:
    servlet:
      loadOnStartup: 1

---
spring:
  profiles: local

---
spring:
  profiles: dev

---
spring:
  profiles: prod