spring:
  profiles:
    active: local
  mvc:
    servlet:
      loadOnStartup: 1
  application:
    name: sc-sba
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9876
  contextPath: /
---
spring:
  profiles: local

---
spring:
  profiles: dev

---
spring:
  profiles: prod