feign:
  hystrix:
    enabled: 1
  sentinel:
    enabled: true
# feign.hystrix.enabled的值在依赖了Sleuth和依赖Sentinel需要将其设置为一个既不是true也不是false的值！！
# false --> TraceFeignClientAutoConfiguration.feignBuilder
# true  --> TraceFeignClientAutoConfiguration.feignHystrixBuilder，但可以将Hystrix-core排除掉
# FeignClientsConfiguration.HystrixFeignConfiguration先查找parentBeanFactory，此时将Sentinel fein打开就可以了
